### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by Sword-Smith** [GeorgeKimionis/BitcoinLib#116]
If this repo is not maintained I would be happy to take over. I have a decent track record wrt contributions to this library.

**Comment by moodmosaic** [comment]
It is (maintained), in the sense that pull requests are reviewed and accepted, and issues are monitored.

But, if you could help keep it up to date with the latest Bitcoin Core versions, and push new versions up on NuGet it'd be great :100: 

@kimionis do you agree? If so, we can grand push-access to @Sword-Smith, both here and on NuGet.

**Comment by xeniacx** [comment]
Absolutely, by all means. Thank you both for your contribution.

**Comment by moodmosaic** [comment]
Great! I'll see if I have all permissions to setup @Sword-Smith, if not I'll reach back to you, @kimionis.

**Comment by moodmosaic** [comment]
@Sword-Smith, I scheduled for today to add you as maintainer on this repository and also give you push-access on NuGet (assuming you also want to do the NuGet releases yourself).

Sounds good? :smiley:

**Comment by Sword-Smith** [comment]
Sounds great! 👍

**Comment by moodmosaic** [comment]
@Sword-Smith, you should be all set. Once you're close doing a NuGet release you should get push-access there as well (the NuGet account is managed by @kimionis).

Once again, *thank you*! Feel free to ask (me or @kimionis) about any questions you might have, or if you just need a second opinion just ping us on issue(s)/or pull request(s). :beers:
