### ISSUE TITLE
Issue? / workaround inside public T MakeRequest<T> !?

### ISSUE THREAD

**Issue by 3strategy** [GeorgeKimionis/BitcoinLib#14]
public T MakeRequest<T>(RpcMethods rpcMethod, params object[] parameters)  sometimes throws a null reference exception when trying to return rpcResponse.Result; (it's the .Error that contains info in these cases).
In my personal version, I implemented a workaround, if (rpcResponse == null) return default(T);
1: I wish to avoid a "personal version", but 2: not sure my workaround is a correct approach.

Please let me know if "return default(T);" is a correct approach in this null result, or should I catch the exception at my application level (which for me would translate to multiple locations). I'm suspecting I'm using a wrong approach. 
When I think of it, the best for me is that in case there's a null reference exception, the application would somehow have access to the full Json response (instead of just the exception or just a default(T) that I'm returning. The reason is that we need to let the application "see" the error property that's in the Json.  

below is my current workaround code. Waiting to read your thoughts.

public T MakeRequest<T>(RpcMethods rpcMethod, params object[] parameters)
        {
            JsonRpcResponse<T> rpcResponse = MakeRpcRequest<T>(new JsonRpcRequest(1, rpcMethod.ToString(), parameters), 0);
            if (rpcResponse == null)
                return default(T);
            else
                return rpcResponse.Result;

**Comment by GeorgeKimionis** [comment]
This is now resolved with the use of `RpcInternalServerErrorException()` that handle internal server error exceptions and rebroadcast both the error message as well as the rpc error code.
