### ISSUE TITLE
Required parameters?

### ISSUE THREAD

**Issue by LeCoffee** [GeorgeKimionis/BitcoinLib#15]
(note: not really a bug just a little confused)
So I'm connecting to Dogecoin at runtime and I cant really use a file like app.config which I see is what is used in the console example. What I have at the moment is this:
```c#
ICryptocoinService cryptocoinService;
try {
	cryptocoinService = new CryptocoinService("myhost", "myuser", "mypass");
	cryptocoinService.Parameters.RpcRequestTimeoutInSeconds = 10;
	cryptocoinService.Parameters.RpcResendTimedOutRequests = true;
	cryptocoinService.Parameters.RpcTimedOutRequestsResendAttempts = 5;
	cryptocoinService.Parameters.RpcDelayResendingTimedOutRequests = true;                    cryptocoinService.Parameters.RpcUseBase2ExponentialDelaysWhenResendingTimedOutRequests = true;
	cryptocoinService.Parameters.RpcUnlockWalletImplicitlyWhenRequired = true;
        cryptocoinService.Parameters.CoinLongName = "Dogecoin";
	cryptocoinService.Parameters.CoinShortName = "Doge";
	cryptocoinService.Parameters.IsoCurrencyCode = "XDG";
	cryptocoinService.Parameters.UseTestnet = false;

} catch(Exception e1) {
	Log.Error (e1.Message); // Custom class I have you'll ned to use Console.log here
}
```

and I seem to be getting this:
```
[01-09-2014 20:55:32] ERROR: One or more required parameters, as defined in CoinParameters, were not found in the configuration file!
```

So just what are the required parameters? And how would one obtain them?
I have looked in the "CoinParameters" class and there are a lot of parameters do I need all of them?

**Comment by GeorgeKimionis** [comment]
This is now resolved with the use of the [`IgnoreConfigValues` parameter](https://github.com/GeorgeKimionis/BitcoinLib/blob/daaa61d7e0db1708604a15266d949581ec212862/CoinWrapper/CoinParameters/Base/CoinParameters.cs#L169) which must be set `true` upon initialization and then the [6 shared RPC config values](https://github.com/GeorgeKimionis/BitcoinLib/blob/daaa61d7e0db1708604a15266d949581ec212862/CoinWrapper/CoinParameters/Base/CoinParameters.cs#L29) as well as the config values for each coin ([Bitcoin](https://github.com/GeorgeKimionis/BitcoinLib/blob/daaa61d7e0db1708604a15266d949581ec212862/CoinWrapper/CoinParameters/Base/CoinParameters.cs#L50), [Litecoin](https://github.com/GeorgeKimionis/BitcoinLib/blob/daaa61d7e0db1708604a15266d949581ec212862/CoinWrapper/CoinParameters/Base/CoinParameters.cs#L89), etc) have to be defined at run-time.

**Comment by LeCoffee** [comment]
Alrighty, thanks for the update!

**Comment by Affinity121** [comment]
Do not quite understand how `IgnoreConfigValues` works. I am unable to set it before `new BitcoinService`, because it is part of `BitcoinService` object, but `new BitcoinService` throws the exception if `IgnoreConfigValues` is not set. Vicious circle.

**Comment by Affinity121** [comment]
I forced to edit `IgnoreConfigValues` property directly in your code.

**Comment by GeorgeKimionis** [comment]
Here is some sample code for `IgnoreConfigValues`. To test it go to the demo app's `app.config` and remove all config values under the `Bitcoin settings` section, then add this to `Main()` and run it:

            ICoinService CoinService = new BitcoinService(useTestnet:true);
            CoinService.Parameters.IgnoreConfigValues = true;

            CoinService.Parameters.DaemonUrl = "http://localhost:8332";
            CoinService.Parameters.DaemonUrlTestnet = "http://localhost:18332";
            CoinService.Parameters.WalletPassword = "MyWalletPassword";
            CoinService.Parameters.RpcUsername = "MyRpcUsername";
            CoinService.Parameters.RpcPassword = "MyRpcPassword";

**Comment by Affinity121** [comment]
Let's assume I do not have `app.config` file. First I do `IBitcoinService bitcoinService = new BitcoinService(.........)`. As I see internally it calls `CoinService(.....)`. Then `CoinService(.....)` calls parameterless `CoinService()`. Then parameterless `CoinService()` calls `new CoinParameters(this)` and finally `CoinParameters(....)` tries to read from `AppSettings` and crashes. Am I correct?

**Comment by GeorgeKimionis** [comment]
Nice catch. With the [latest commit](https://github.com/GeorgeKimionis/BitcoinLib/commit/f33a738c997b597327c8537a7b808020e2bd7056) you can choose to ignore the `.config` files by invoking the coin service like this: 
`ICoinService CoinService = new BitcoinService("http://localhost:18332", "MyRpcUsername", "MyRpcPassword", "MyWalletPassword", 60);`.

This: `ICoinService CoinService = new BitcoinService(useTestnet:true);` will still use the `.config` facility.

**Comment by r00tn** [comment]
Hey, still got the issue.
It tells, that i am missing parameters, but i am using the example appSettings section.
Also when i try to create a new BitcoinService instance with entering the parameters on the concstructor it fails with same message.

Got the package from NuGet.

**Comment by HellsChicken** [comment]
Same issue as r00tn.  I can't construct using the example from the 27th because it tells me that no constructor takes 5 parameters. Even if I use the example .config file, I still get this error.

**Comment by surchello** [comment]
it's funny that it will work if you build the solution using debug configuration instead of release.
