### ISSUE TITLE
web response dispose?

### ISSUE THREAD

**Issue by Chaz27** [GeorgeKimionis/BitcoinLib#24]
Hi,

Is there any reason the web response is not wrapped in a using block?

https://github.com/GeorgeKimionis/BitcoinLib/blob/master/CoinWrapper/RPC/Connector/RpcConnector.cs#L68

Cheers,
Chaz

**Comment by GeorgeKimionis** [comment]
Hey Chaz, no, none that I can think of. The `WebResponse` should be wrapped into a `using` block, it must have been left out during the last refactoring. I will be pushing an update in a moment, thanks for bringing this up.
