### ISSUE TITLE
getbalance always return 0.000000000000

### ISSUE THREAD

**Issue by micax** [GeorgeKimionis/BitcoinLib#25]
for example:

neither
var balance = BitcoinService.GetBalance(address, 1, true);
nor
var balance = BitcoinService.GetBalance(address);

does not return correct balance - but only 0.000000000

**Comment by GeorgeKimionis** [comment]
`GetBalance` doesn't take `address` as a parameter. Please consult the [method definition](https://github.com/GeorgeKimionis/BitcoinLib/blob/7dd051d343d297a3ac725337e3830c603d8dcee3/CoinWrapper/Services/RpcServices/RpcService/IRpcService.cs#L31) before opening an issue here. [This](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list) might also be useful.
