### ISSUE TITLE
getWalletInfoResponse

### ISSUE THREAD

**Issue by GereG** [GeorgeKimionis/BitcoinLib#27]
getWalletInfoResponse is missing keyPoolSize atribute.
from
https://bitcoin.org/en/developer-reference#getwalletinfo

**Comment by GeorgeKimionis** [comment]
Nice catch! [Fixed](https://github.com/GeorgeKimionis/BitcoinLib/commit/ff058011f0f8e5f1b994934619f2990f8263ff9a).
