### ISSUE TITLE
bitcoin.conf, location on a MAC ?

### ISSUE THREAD

**Issue by appsolutegeek** [GeorgeKimionis/BitcoinLib#33]
Hi,

Where is the following bitcoin.conf file stored on a mac, I notice on the front page it gives the info of where i should find it on Windows but i currently use a mac.

thanks

**Comment by moodmosaic** [comment]
It should be under

```
$HOME/Library/Application Support/Bitcoin/
```

See also: https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File.
