### ISSUE TITLE
Release and Debug builds are different

### ISSUE THREAD

**Issue by surchello** [GeorgeKimionis/BitcoinLib#40]
This is related to https://github.com/GeorgeKimionis/BitcoinLib/issues/15.
For example, BitcoinService has differetn constructors in release and debug, Looks like debug is newer than release and NuGet package. Is it safe to use current debug build in production?

**Comment by moodmosaic** [comment]
We're working on getting releases out the door more frequently, via #31. Meanwhile, [we just released v1.3.4](https://www.nuget.org/packages/BitcoinLib/1.3.4). These are all based on the `Release` configuration.

---

`Debug` and `Release` are currently the same; that is, no compiler directives based on `DEBUG` flag, but those on `Release` are more optimized:

* the C# compiler doesn't emit symbols for all variables and doesn't compile the code as-is
* unused variables do not get compiled at all
* some loop variables are taken out of the loop by the compiler if they are proven to be invariants
* code written under `#DEBUG` directives is not included

[The rest is up to the JIT.](https://stackoverflow.com/questions/2446027/debug-vs-release-performance)

---

Closing this, as there's now a current version available. Feel free to reopen it, or add comment to it.
