### ISSUE TITLE
Support for BCH?

### ISSUE THREAD

**Issue by hawthornetr** [GeorgeKimionis/BitcoinLib#41]
Quick update for BCH support?

**Comment by milkeg** [comment]
Using CryptocoinService type, you can already communicate with a BCH node without any issue (as BCH is a recent fork of BTC):

```
            var CoinService = new CryptocoinService(UtxoNodeUri, UtxoRpcUsername, UtxoRpcPassword,
                null, UtxoRpcTimeoutInSeconds);
```

**Comment by moodmosaic** [comment]
Closing this, based on @milkeg's comment. Feel free to reopen this, or add comments to it, if needed.
