### ISSUE TITLE
.NET Core Error = "One or more required parameters, as defined in CoinParameters, were not found in the configuration file!"

### ISSUE THREAD

**Issue by Serjster** [GeorgeKimionis/BitcoinLib#42]
It seems to force me to use the xml settings specifically, even when I pass in the settings in the constructor:

`new BitcoinService(appSettings.Bitcoin.ServerUrl,
                                appSettings.Bitcoin.Username,
                                appSettings.Bitcoin.Password,
                                appSettings.Bitcoin.WalletPassword);`

It still tries to read from the settings file, throwing the error:

> One or more required parameters, as defined in CoinParameters, were not found in the configuration file!

 There's an `IgnoreConfigFiles` but there's no way for me to interact with it...

**Comment by Serjster** [comment]
BTW, I'm using version 1.3.3 of BitcoinLib.

I've put these settings both inside and outside of AppSettings in appsettings.json:

"AppSettings": {
        "Bitcoin_DaemonUrl": "http://localhost:18332",
        "Bitcoin_RpcUsername": "X",
        "Bitcoin_RpcPassword": "X",
        "Bitcoin_WalletPassword": "X"
}

In the demo I can see that it is still using the old school xml deal... is there no way to instanstiate a client without using the xml?

**Comment by Serjster** [comment]
I did end up finding a solution. The actual problem was that the timeout was always set to 0. Not sure why VS was showing the wrong exception... you can learn more about this here: https://stackoverflow.com/q/47147440/550975

**Comment by Serjster** [comment]
I did create a .NET Core compatible version, you can see the repo here:
https://github.com/SaganMarketing/BitcoinLib

and can get a package here:
https://www.myget.org/feed/saganmarketing/package/nuget/BitcoinLib

**Comment by moodmosaic** [comment]
>I did create a .NET Core compatible version, you can see the repo here:

That's great! BTW, it looks like [many stuff have been removed](https://github.com/GeorgeKimionis/BitcoinLib/compare/master...SaganMarketing:master) in that .NET Standard fork. Are all these changes necessary? 😕 

If you can come up with just the minimum required changes, we could happily take them as a pull request 🚀

**Comment by moodmosaic** [comment]
This is now resolved in [v1.3.4](https://www.nuget.org/packages/BitcoinLib/1.3.4). Based on your [comment](https://stackoverflow.com/questions/47147440/getting-bitcoinlib-error-one-or-more-required-parameters-as-defined-in-coinp?noredirect=1#comment81293392_47147440), I think we should close this. Feel free to reopen this or add comments to it, if needed.

---

About the .NET Standard version, we're working on it. Stay tuned 🚀
