### ISSUE TITLE
AddWitnessAddress request

### ISSUE THREAD

**Issue by PuL9** [GeorgeKimionis/BitcoinLib#45]
Very useful function

**Comment by moodmosaic** [comment]
While it's easy to add that call to this library, keep in mind https://github.com/bitcoin/bitcoin/pull/11400/ as I'm pretty sure you'll get an error saying "Segregated witness not enabled on network".

**Comment by PuL9** [comment]
It's fine if it will give me error when it's not enabled, this function is still pretty needed for me.

**Comment by moodmosaic** [comment]
Add in d904cee and released as BitcoinLib 1.4.0 on NuGet.
