### ISSUE TITLE
Unable to resolve dependencies. 'Newtonsoft.Json 10.0.3' is not compatible with 'BitcoinLib 1.4.1

### ISSUE THREAD

**Issue by mziii** [GeorgeKimionis/BitcoinLib#50]
Install-Package : Unable to resolve dependencies. 'Newtonsoft.Json 10.0.3' is not compatible with 'BitcoinLib 1.4.1 constraint: Newtonsoft.Json (= 6.0.3)'.
At line:1 char:1
+ Install-Package BitcoinLib

**Comment by moodmosaic** [comment]
Fixed in e54461a and released as [BitcoinLib 1.4.2](https://www.nuget.org/packages/BitcoinLib/1.4.2).
