### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by moodmosaic** [GeorgeKimionis/BitcoinLib#52]
BitcoinLib should *also* target .NET Standard, similar to what's discussed in

- https://github.com/dotnet/cli/issues/4874
- https://github.com/SwensenSoftware/unquote/pull/136

**Comment by moodmosaic** [comment]
Just pushed [`netstandard20`](https://github.com/GeorgeKimionis/BitcoinLib/tree/netstandard20) branch with support for .NET Standard 2.0 🚀 It'd be great if you can test it before we can merge this into `master` /cc @weitaolee @Serjster @nixxholas

**Comment by nixxholas** [comment]
Roger, will be on my pipeline today for checks. Send you a beep in <8 hours

**Comment by moodmosaic** [comment]
>Roger, will be on my pipeline today for checks. Send you a beep in <8 hours

Did it work for you? Would be nice to know what environment you use (e.g. Ubuntu, VS Code, etc.) 🎉

**Comment by nixxholas** [comment]
> Did it work for you? Would be nice to know what environment you use (e.g. Ubuntu, VS Code, etc.) 🎉

Yes it did! However, I was using the submodule approach, loading it with a local NuGet server gave no problems either.

VS Studio for Mac (Enterprise)
Tested on VS Studio Windows as well, and dotnet cli builds (CI)

**Comment by moodmosaic** [comment]
Amazing news, then 😃 Once we figure out why Travis CI fails and the git submodules thing you propose, we should be good to go. Perhaps we should give @weitaolee and @Serjster some time to test too.

**Comment by Serjster** [comment]
I should be able to check it out tonight

**Comment by nixxholas** [comment]
Standby for pull request in the next 12 hours

**Comment by moodmosaic** [comment]
No worries. I'll fix Travis CI in the meantime.

**Comment by nixxholas** [comment]
@moodmosaic one liner for submodule compatbility... haha https://github.com/GeorgeKimionis/BitcoinLib/pull/56

**Comment by moodmosaic** [comment]
@nixxholas https://github.com/GeorgeKimionis/BitcoinLib/pull/56#pullrequestreview-83804186

**Comment by thangchung** [comment]
+1
