### ISSUE TITLE
Can I use bip39 and Mnemonic wallets?

### ISSUE THREAD

**Issue by coinpennant** [GeorgeKimionis/BitcoinLib#57]
Hi,

can I use with your project bip39 and Mnemonic wallets?

**Comment by moodmosaic** [comment]
No, IIRC, Bitcoin Core generates random private keys to be used as receiving and change addresses, contrary to deterministic (BIP39) wallets that can generate an unlimited number of addresses on the fly. 

@GeorgeKimionis might have a better idea though.

**Comment by coinpennant** [comment]
hmm do you have an example how to generate random private keys for DASH?

**Comment by moodmosaic** [comment]
No, I don't have one. (Closing this as it isn't an issue per se. Feel free to add comments to it, or reopen it.)
