### ISSUE TITLE
LICENSE doesn't look like open source

### ISSUE THREAD

**Issue by coinnail** [GeorgeKimionis/BitcoinLib#62]
Is the current license updated as intended?

It reads like a closed source license and not like a open-source license. I don't think I can even make a fork of this in GitHub.

On the Preamble:
> without the rights to create derivative works

On the Permitted Use and Restrictions:
> shall not distribute, sell or transfer the Software or Improvements to any person or third parties without prior written permission from the Licensor.

On the Ownership and Assignment of Copyright:
> The Licensee agrees to use its reasonable best efforts to protect the contents of the Software and to prevent unauthorized disclosure by its agents, officers, employees, and consultants

On the Copies:
> The Licensee may make a reasonable number of copies of the Software for the purposes of backup and maintenance of the Software

**Comment by GeorgeKimionis** [comment]
To keep it simple: do what you like as long as it is for educational or nonprofit purposes. Commercial and/or for-profit applications require a license.
