### ISSUE TITLE
Add ListTransactionsResponse.Label field

### ISSUE THREAD

**Issue by GSPP** [GeorgeKimionis/BitcoinLib#64]
`ListTransactions` should return the label field. I'm not in a position to make a pull request right now so here's the new source code:

```
    public class ListTransactionsResponse
    {
        public string Account { get; set; }
        public string Address { get; set; }
        public string Category { get; set; }
        public decimal Amount { get; set; }
        public string Label { get; set; }
        public int Vout { get; set; }
        public decimal Fee { get; set; }
        public int Confirmations { get; set; }
        public string BlockHash { get; set; }
        public int BlockIndex { get; set; }
        public int BlockTime { get; set; }
        public string TxId { get; set; }
        public List<string> WalletConflicts { get; set; }
        public int Time { get; set; }
        public int TimeReceived { get; set; }
        public string Comment { get; set; }
        public string OtherAccount { get; set; }
        public bool InvolvesWatchonly { get; set; }
        public bool Abandoned { get; set; }
    }
```

I also fixed `double` to `int` and added a new field `bool Abandoned` which I found returned in the current version of Bitcoin Core.

**Comment by moodmosaic** [comment]
Thanks! We may take this on and release it on NuGet. It'd be awesome with a pull request, so you can keep track of your contribution(s), but it's totally fine if you can't. :+1: :rocket: :100:

**Comment by moodmosaic** [comment]
Done in https://github.com/GeorgeKimionis/BitcoinLib/pull/70. Thank you.

**Comment by GSPP** [comment]
I saw you applied the label but not the double to int change. I think the double change should be made as well because these values fundamentally are ints. I think the compatibility impact is low because even if user code must be changed the change is trivial (likely remove a cast to int).

If you want to I'll make a pull request.

**Comment by moodmosaic** [comment]
It's always awesome with a PR 👍 💯 Please go for it 🚀
